In [1]:
import pandas as pd

In [2]:
column_headers = ["date","timestamp","open","high","low","close","volume"]
filename = "/mnt/c/Shaukat/code_repo/HighFrequencyTradingCoding/data/DAT_MT_AUDUSD_M1_202411.csv"
df = pd.read_csv(filename, names=column_headers)

# combine dates and timestamps into single datetime column
df['datetime'] = pd.to_datetime(df['date'] + ' ' + df['timestamp'], format='%Y.%m.%d %H:%M')

# drop date, timestamp and volume
df.drop(columns=["date", "timestamp", "volume"], inplace=True)

# Setting datetime as index
df.set_index("datetime", inplace=True)

In [3]:
df.head(5)

                        open     high      low    close
datetime
2024-11-03 17:00:00  0.66094  0.66125  0.66079  0.66094
2024-11-03 17:01:00  0.66094  0.66123  0.66076  0.66076
2024-11-03 17:02:00  0.66077  0.66077  0.66036  0.66067
2024-11-03 17:03:00  0.66067  0.66067  0.66065  0.66066
2024-11-03 17:04:00  0.66060  0.66070  0.66039  0.66070

In [4]:
# Add last lag_minutes minutes
lag_minutes = 3
for iter_lag in range(1,lag_minutes):
    # print(iter_lag)
    df[f"open_t-{iter_lag}"] = df["open"].shift(iter_lag)
    df[f"open_avg_t-{iter_lag}"] = df["open"].rolling(window=iter_lag).mean()
    df[f"high_t-{iter_lag}"] = df["high"].shift(iter_lag)
    df[f"low_t-{iter_lag}"] = df["low"].shift(iter_lag)
    df[f"close_t-{iter_lag}"] = df["close"].shift(iter_lag)
# df["open_t-1"] = df["open"].shift(1)

In [5]:
df.head(5)

,open,high,low,close,open_t-1,open_avg_t-1,high_t-1,low_t-1,close_t-1,open_t-2,open_avg_t-2,high_t-2,low_t-2,close_t-2
datetime,,,,,,,,,,,,,,
2024-11-03 17:00:00,0.66094,0.66125,0.66079,0.66094,NaN,0.66094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11-03 17:01:00,0.66094,0.66123,0.66076,0.66076,0.66094,0.66094,0.66125,0.66079,0.66094,NaN,0.660940,NaN,NaN,NaN
2024-11-03 17:02:00,0.66077,0.66077,0.66036,0.66067,0.66094,0.66077,0.66123,0.66076,0.66076,0.66094,0.660855,0.66125,0.66079,0.66094
2024-11-03 17:03:00,0.66067,0.66067,0.66065,0.66066,0.66077,0.66067,0.66077,0.66036,0.66067,0.66094,0.660720,0.66123,0.66076,0.66076
2024-11-03 17:04:00,0.66060,0.66070,0.66039,0.66070,0.66067,0.66060,0.66067,0.66065,0.66066,0.66077,0.660635,0.66077,0.66036,0.66067

In [6]:
# Add price label
df['label'] = df.apply(lambda row: 1 if row['close'] > row['open'] else 0, axis=1)

In [7]:
df.head(5)

,open,high,low,close,open_t-1,open_avg_t-1,high_t-1,low_t-1,close_t-1,open_t-2,open_avg_t-2,high_t-2,low_t-2,close_t-2,label
datetime,,,,,,,,,,,,,,,
2024-11-03 17:00:00,0.66094,0.66125,0.66079,0.66094,NaN,0.66094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2024-11-03 17:01:00,0.66094,0.66123,0.66076,0.66076,0.66094,0.66094,0.66125,0.66079,0.66094,NaN,0.660940,NaN,NaN,NaN,0
2024-11-03 17:02:00,0.66077,0.66077,0.66036,0.66067,0.66094,0.66077,0.66123,0.66076,0.66076,0.66094,0.660855,0.66125,0.66079,0.66094,0
2024-11-03 17:03:00,0.66067,0.66067,0.66065,0.66066,0.66077,0.66067,0.66077,0.66036,0.66067,0.66094,0.660720,0.66123,0.66076,0.66076,0
2024-11-03 17:04:00,0.66060,0.66070,0.66039,0.66070,0.66067,0.66060,0.66067,0.66065,0.66066,0.66077,0.660635,0.66077,0.66036,0.66067,1

In [8]:
# Remove Nans
df.dropna(inplace=True)

In [9]:
df.head(12)

,open,high,low,close,open_t-1,open_avg_t-1,high_t-1,low_t-1,close_t-1,open_t-2,open_avg_t-2,high_t-2,low_t-2,close_t-2,label
datetime,,,,,,,,,,,,,,,
2024-11-03 17:02:00,0.66077,0.66077,0.66036,0.66067,0.66094,0.66077,0.66123,0.66076,0.66076,0.66094,0.660855,0.66125,0.66079,0.66094,0
2024-11-03 17:03:00,0.66067,0.66067,0.66065,0.66066,0.66077,0.66067,0.66077,0.66036,0.66067,0.66094,0.660720,0.66123,0.66076,0.66076,0
2024-11-03 17:04:00,0.66060,0.66070,0.66039,0.66070,0.66067,0.66060,0.66067,0.66065,0.66066,0.66077,0.660635,0.66077,0.66036,0.66067,1
2024-11-03 17:05:00,0.66069,0.66069,0.66056,0.66069,0.66060,0.66069,0.66070,0.66039,0.66070,0.66067,0.660645,0.66067,0.66065,0.66066,0
2024-11-03 17:06:00,0.66069,0.66069,0.66052,0.66055,0.66069,0.66069,0.66069,0.66056,0.66069,0.66060,0.660690,0.66070,0.66039,0.66070,0
2024-11-03 17:07:00,0.66054,0.66055,0.66039,0.66039,0.66069,0.66054,0.66069,0.66052,0.66055,0.66069,0.660615,0.66069,0.66056,0.66069,0
2024-11-03 17:08:00,0.66039,0.66087,0.66039,0.66084,0.66054,0.66039,0.66055,0.66039,0.66039,0.66069,0.660465,0.66069,0.66052,0.66055,1
2024-11-03 17:09:00,0.66085,0.66094,0.66085,0.66090,0.66039,0.66085,0.66087,0.66039,0.66084,0.66054,0.660620,0.66055,0.66039,0.66039,1
2024-11-03 17:10:00,0.66089,0.66090,0.66046,0.66046,0.66085,0.66089,0.66094,0.66085,0.66090,0.66039,0.660870,0.66087,0.66039,0.66084,0
2024-11-03 17:11:00,0.66054,0.66059,0.66051,0.66055,0.66089,0.66054,0.66090,0.66046,0.66046,0.66085,0.660715,0.66094,0.66085,0.66090,1
2024-11-03 17:12:00,0.66055,0.66056,0.66044,0.66045,0.66054,0.66055,0.66059,0.66051,0.66055,0.66089,0.660545,0.66090,0.66046,0.66046,0
2024-11-03 17:13:00,0.66045,0.66045,0.66017,0.66017,0.66055,0.66045,0.66056,0.66044,0.66045,0.66054,0.660500,0.66059,0.66051,0.66055,0